[package]
name = "raytracer"
version = "0.1.0"
authors = ["voidptr"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stb_image = "0.2.2"

[dependencies.rand]
version = "0.7.0"
features = ["small_rng"]
